default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hobo-rails_development

test:
  <<: *default
  database: hobo-rails_test

production:
  <<: *default
  database: hobo-rails_production
  username: hobo-rails
  password: <%= ENV['HOBO-RAILS_DATABASE_PASSWORD'] %>
